#!/usr/bin/python

import gettext
import getopt
import sys

gettext.install("unknownhorizons", unicode=1)

import os
from horizons import main

positions = ['/usr/share/games',
	  '/usr/share',
	  '/usr/local/share/games',
	  '/usr/local/share',
	  ]

pos = ''

for i in positions:
    if os.path.exists('%s/unknown-horizons' % i):
       pos = i
       break

os.chdir('%s/unknown-horizons' % pos)

def print_help():
	print _("Unknown Horizons usage:")
	print "run_uh.py [-d] [-h]"
	print ""
	print _("Options:")
	print "-d --debug   -", _("Debug, enables debug output, useful for testing.")
	print "-h --help    -", _("Print this help message.")
	print ""
	print _("Have fun playing, and if you do, help us developing!")

try:
    opts, args = getopt.getopt(sys.argv[1:], "hd", \
                                   ["help", "debug", "fife-in-library-path", "start-dev-map"])
except getopt.GetoptError, err:
    print str(err)
    print_help()
    exit(1)
    
debug = False
fife_in_library_path = False

command_line_arguments = { "start_dev_map": False, \
                               "start_map": None, \
                               "unstable_features": False}

# apply arguments
for o, a in opts:
    if o in ("-h", "--help"):
        print_help()
        exit(1)
    elif o in ("-d", "--debug"):
        debug = True
    elif o == "--fife-in-library-path":
        # this is currently only for internal use, therefore not in the help message
        fife_in_library_path = True
    elif o == "--start-dev-map":
        # automatically starts development map
        command_line_arguments['start_dev_map'] = True
    elif o == "--start-map":
        # start map selected by commandline arg
        command_line_arguments['start_map'] = a
    elif o == "--enable-unstable-features":
        command_line_arguments["unstable_features"] = True

print _("Launching Unknown Horizons")

main.debug = False

main.start(command_line_arguments)
