CREATE TABLE "citynames" (
	"name" TEXT NOT NULL,
	"for_pirate" BOOL NOT NULL DEFAULT ('0'),
	"for_player" BOOL NOT NULL DEFAULT ('0'),
	"locale" TEXT NOT NULL DEFAULT ('en')
);
INSERT INTO "citynames" VALUES('St. Petrus',0,1,'en');
INSERT INTO "citynames" VALUES('Jagstursprung',1,0,'en');
INSERT INTO "citynames" VALUES('New Xanten',0,1,'en');
INSERT INTO "citynames" VALUES('Port Foobar',0,1,'en');
INSERT INTO "citynames" VALUES('St. Polten',0,1,'en');
INSERT INTO "citynames" VALUES('New Crailsheim',0,1,'en');
INSERT INTO "citynames" VALUES('Port Sollerup',0,1,'en');
INSERT INTO "citynames" VALUES('New Montabaur',0,1,'en');
INSERT INTO "citynames" VALUES('New Cologne',0,1,'en');
INSERT INTO "citynames" VALUES('New Nuremberg',0,1,'en');
INSERT INTO "citynames" VALUES('New Amsterdam',0,1,'en');
INSERT INTO "citynames" VALUES('Port Southland',0,1,'en');
INSERT INTO "citynames" VALUES('St. Patrick',0,1,'en');
INSERT INTO "citynames" VALUES('Hamburg Harbour',0,1,'en');
INSERT INTO "citynames" VALUES('London Harbour',0,1,'en');
INSERT INTO "citynames" VALUES('St. Inken',0,1,'en');
INSERT INTO "citynames" VALUES('Santeocalli',0,1,'en');
INSERT INTO "citynames" VALUES('La Paranagua',0,1,'en');
INSERT INTO "citynames" VALUES('Nouvelle-Montroulez',0,0,'en');
INSERT INTO "citynames" VALUES('Punta do Socorro',0,1,'en');
INSERT INTO "citynames" VALUES('Colonia del Este',0,1,'en');
INSERT INTO "citynames" VALUES('Asuncion Novatlan',0,1,'en');
INSERT INTO "citynames" VALUES('Cholulameco',0,1,'en');
INSERT INTO "citynames" VALUES('Rivanabia',0,1,'en');
INSERT INTO "citynames" VALUES('San Sanabria',0,1,'en');
INSERT INTO "citynames" VALUES('Teducihalpes',0,1,'en');
INSERT INTO "citynames" VALUES('Xoxochetun',0,1,'en');
INSERT INTO "citynames" VALUES('Port Royal',1,0,'en');
INSERT INTO "citynames" VALUES('Tortuga',1,0,'en');
INSERT INTO "citynames" VALUES('Porta Bravo',0,1,'en');
INSERT INTO "citynames" VALUES('Porta del Sol',0,1,'en');
INSERT INTO "citynames" VALUES('Porta Atlantica',0,1,'en');
INSERT INTO "citynames" VALUES('Porta Lino',0,1,'en');
INSERT INTO "citynames" VALUES('Blackport',1,0,'en');
INSERT INTO "citynames" VALUES('Freetown',1,0,'en');
INSERT INTO "citynames" VALUES('New Viersen',0,1,'en');
INSERT INTO "citynames" VALUES('St. Elmo',0,1,'en');
INSERT INTO "citynames" VALUES('St. Antonio',0,1,'en');
INSERT INTO "citynames" VALUES('New Holland',0,1,'en');
INSERT INTO "citynames" VALUES('Botany Bay',0,1,'en');
INSERT INTO "citynames" VALUES('Batavia',1,0,'en');
INSERT INTO "citynames" VALUES('Fogwaters',1,0,'en');
INSERT INTO "citynames" VALUES('Rum Reef Refuge',1,0,'en');
INSERT INTO "citynames" VALUES('Treasure Gate',1,0,'en');
INSERT INTO "citynames" VALUES('Ghost Piers',1,0,'en');
INSERT INTO "citynames" VALUES('Port Velar',0,1,'en');
INSERT INTO "citynames" VALUES('Wharf Eddy',1,0,'en');
INSERT INTO "citynames" VALUES('St. Anne',0,1,'en');
INSERT INTO "citynames" VALUES('St. Laurens',0,1,'en');
INSERT INTO "citynames" VALUES('St. Peters',0,1,'en');
INSERT INTO "citynames" VALUES('Cap-Rouge',0,1,'en');
INSERT INTO "citynames" VALUES('Charlesfort',0,1,'en');
INSERT INTO "citynames" VALUES('Fort Caroline',0,1,'en');
INSERT INTO "citynames" VALUES('Tadoussac',0,1,'en');
INSERT INTO "citynames" VALUES('Fort SaINT Louis',0,1,'en');
INSERT INTO "citynames" VALUES('SaINT-Domingue',0,1,'en');
INSERT INTO "citynames" VALUES('Marie-Galante',0,1,'en');
INSERT INTO "citynames" VALUES('Martinique',0,1,'en');
INSERT INTO "citynames" VALUES('St. Croix',0,1,'en');
INSERT INTO "citynames" VALUES('St. Kitts',0,1,'en');
INSERT INTO "citynames" VALUES('St. Lucia',0,1,'en');
INSERT INTO "citynames" VALUES('St. Martin',0,1,'en');
INSERT INTO "citynames" VALUES('St. Vincent',0,1,'en');
INSERT INTO "citynames" VALUES('Tobago',0,1,'en');
INSERT INTO "citynames" VALUES('St. Eustatius',0,1,'en');
INSERT INTO "citynames" VALUES('Los Roques',0,1,'en');
INSERT INTO "citynames" VALUES('La Orchila',0,1,'en');
INSERT INTO "citynames" VALUES('Bonaire',0,1,'en');
INSERT INTO "citynames" VALUES('Saba',0,1,'en');
INSERT INTO "citynames" VALUES('St. Thomas',0,1,'en');
INSERT INTO "citynames" VALUES('St. John',0,1,'en');
INSERT INTO "citynames" VALUES('Santa Ana de Cor',0,1,'en');
INSERT INTO "citynames" VALUES('Seville',0,1,'en');
INSERT INTO "citynames" VALUES('Santo Domingo',0,1,'en');
INSERT INTO "citynames" VALUES('Brandenburg',0,1,'en');
INSERT INTO "citynames" VALUES('Alta Verapaz',0,1,'en');
INSERT INTO "citynames" VALUES('Pozuzo',0,1,'en');
INSERT INTO "citynames" VALUES('Oxapampa',0,1,'en');
INSERT INTO "citynames" VALUES('Recife',0,1,'en');
INSERT INTO "citynames" VALUES('St. Barthelemy',0,1,'en');
INSERT INTO "citynames" VALUES('Bogwaters',1,0,'en');
INSERT INTO "citynames" VALUES('Port la Riqueza',1,0,'en');

CREATE TABLE "groundunitnames" (
	"name" TEXT NOT NULL,
	"locale" TEXT NOT NULL DEFAULT ('en')
);
INSERT INTO "groundunitnames" VALUES('Robin Hood','en');
INSERT INTO "groundunitnames" VALUES('Klaus Stoertebeker','de');
INSERT INTO "groundunitnames" VALUES('Blackbeard','en');

CREATE TABLE "shipnames" (
	"name" TEXT NOT NULL,
	"for_player" BOOL NOT NULL DEFAULT ('0'),
	"for_pirate" BOOL NOT NULL DEFAULT ('0'),
	"for_fisher" BOOL NOT NULL DEFAULT ('0'),
	"for_trader" BOOL NOT NULL DEFAULT ('0'),
	"locale" TEXT NOT NULL DEFAULT ('en')
);
INSERT INTO "shipnames" VALUES('Penelope',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Endeavour',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Surprise',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Acheron',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Xanthos',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Galliwasp',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Tracker',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Antigone',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Patrician',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Bruizer',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Renown',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Caroline',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Indefatigable',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Black Pearl',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Black Hawk',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Dancing Betty',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Red Phoenix',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Flying Dutchman',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Bloody Mary',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('The Bearded Lady',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Huitzilopochtli',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Tonatiuh',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Akhet',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Amarnhaten',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Magna Libertatis',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Navis Nautarum',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Essex',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('Cibus',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('Artis',0,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Adventure',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('INTerceptor',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Enterprise',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Mayflower',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Beagle',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Argo',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Blue Tulip',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Swan of Amsterdam',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Flying Molly',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('Albertros',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('SaINT Peter',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('Neptune',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('Poseidon',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('Triton',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('Silver Tuna',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('Golden Cod',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('Opal Whale',0,0,1,0,'en');
INSERT INTO "shipnames" VALUES('L''Etoile',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Seastar',0,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Resolution',0,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Santa Barbara',0,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Santa Maria',0,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Gallega',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('PINTa',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Santa Clara',0,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Pietro Gonzale',0,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Erasmo',0,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Jodocus',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Cristina de Bolsena',0,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Seewolf',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Queen Anne''s Revenge',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Black Joke',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Blanco',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Cassandra',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Flying Dragon',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Golden Hind',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Good Fortune',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Liberty',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Loyal Fortune',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Ranger',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Revenge',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Rising Sun',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Royal Fortune',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Sea King',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Speedy Return',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Sudden Death',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Victory',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Caleuche',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Dark Maiden',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Night Ram',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Red Sun',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Sea Dragon',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Black Snake',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Surface Shark',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Queen of the Seas',1,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Thunder Dragon',1,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Silver Dragon',1,1,0,0,'en');
INSERT INTO "shipnames" VALUES('The Ghost Dragon',1,1,0,0,'en');
INSERT INTO "shipnames" VALUES('New Hope',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('New Dawn',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('The Mermaid',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Holy Maiden',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Black Thunder',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Black Serpent',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('The Laughing Ghost',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('The Mad King',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('The Dark Maiden',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Victoria',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Carmen',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Jornada',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Fe',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Nassau',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Elisabeth',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Festering Boot',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Cygne Noir',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Los Contaminacao',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Sinspawn',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Keelhaul',0,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Bruynvisch',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Groene Draeck',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Hollandsche Tuin',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Vliegende Draeck',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Vogelstruys',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Vrijheid',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Gerechtigheid',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Gloeyenden Oven',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Tijdverdrijf',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Dolphijn',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Fazant',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Eenhoorn',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Gekroonde Liefde',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Geloof',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Wakende Boei',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Beschermer',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Voorzichtigheid',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Groningen',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Vlissingen',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Walcheren',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Callantsoog',1,0,0,0,'nl');
INSERT INTO "shipnames" VALUES('Ada',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Agnes',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Emma Stonard',1,0,1,1,'en');
INSERT INTO "shipnames" VALUES('Alice',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Alnwick',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Amelia',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Ann Ellen',1,0,1,1,'en');
INSERT INTO "shipnames" VALUES('Ann Summer',1,0,1,1,'en');
INSERT INTO "shipnames" VALUES('Ant',1,0,1,1,'en');
INSERT INTO "shipnames" VALUES('Argus',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Arthur Gordon',1,0,1,1,'en');
INSERT INTO "shipnames" VALUES('Augusta',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Backbarrow',1,1,0,1,'en');
INSERT INTO "shipnames" VALUES('Bans Vale',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Bardsea',1,1,0,1,'en');
INSERT INTO "shipnames" VALUES('Belle',1,0,1,1,'en');
INSERT INTO "shipnames" VALUES('Britannia',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Baron Hill',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Beatrice',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Confidence',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Dove',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Delight',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Dreadnaught',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Emma',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Eugene',1,0,1,1,'en');
INSERT INTO "shipnames" VALUES('Francis',1,1,0,1,'en');
INSERT INTO "shipnames" VALUES('Gauntlet',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Gleaner',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Gratitude',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Glenravil Miner',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Greyhound',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Holy Wath',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Hope',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Hermes',1,1,0,1,'en');
INSERT INTO "shipnames" VALUES('Hare',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Hodbarrow Miner',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Isabella',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Jane',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Kate',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Kitty',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Leo',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Leven',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Mary Jane',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Mary Ann',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Octavia',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Old Hunter',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Rose',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Royal Oak',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Sea King',1,1,0,0,'en');
INSERT INTO "shipnames" VALUES('Squire',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Sirius',1,1,0,1,'en');
INSERT INTO "shipnames" VALUES('Success',1,0,0,0,'en');
INSERT INTO "shipnames" VALUES('Swift',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Tower',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('Wave',1,0,0,1,'en');
INSERT INTO "shipnames" VALUES('William',1,0,1,1,'en');
